name: "legal-assistant-rag"
services:
  lar-db:
    hostname: db
    image: pgvector/pgvector:0.6.0-pg12
    ports:
     - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
     - ./backend/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
     - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
